#!/bin/sh
# update minion

run_salt()
{
	if /sbin/rc-service -qq -e salt-minion
	then
		local n=0
		local m=9

		while [ $n -lt $m ]
		do
			if /bin/ping -qc 1 www.google.com
			then
				break
			fi

			/usr/bin/sleep 30

			/usr/bin/true $(( n++ ))
		done

		if [ $n -lt $m ]
		then
			# deny shutdown/reboot/...
			touch /etc/shutdown.allow
			cp /etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf{.deny,}

			/usr/bin/salt-call state.highstate

			# allow shutdown/reboot/...
			cp /etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf{.allow,}
			rm /etc/shutdown.allow
		fi
	fi
}

run_salt
