#!/bin/sh
# update minion

notify_user()
{
	# config
	DISPLAY=":0"

	/usr/bin/w -husf>>/tmp/salt_blub
	# execute
	USER="$(/usr/bin/w -husf|/usr/bin/awk "\$2 == \"${DISPLAY}\" {print \$1; exit 3}")"

	if [ ${?} -eq 3 ]
	then
		XAUTHORITY="/home/${USER}/.Xauthority"

		export DISPLAY XAUTHORITY

		/usr/bin/zenity --warning \
			--text="Grüße Dich,\n\n\ndas System wird gerade aktualisiert.\n\n\nDeshalb ist das Herunterfahren, Neustarten, etc. zur Zeit nicht erlaubt."
	fi
}

run_salt()
{
	if /sbin/rc-service -qq -e salt-minion
	then
		local n=0
		local m=9

		while [ $n -lt $m ]
		do
			if /bin/ping -qc 1 www.google.com
			then
				break
			fi

			/usr/bin/sleep 30

			/usr/bin/true $(( n++ ))
		done

		if [ $n -lt $m ]
		then
			notify_user

			# /etc/inittab: feature 'shutdown -a'
			# policykit: deny access to its D-Bus connection

			# deny shutdown/reboot/...
			touch /etc/shutdown.allow
			cp /etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf{.deny,}

			/usr/bin/salt-call state.highstate

			# allow shutdown/reboot/...
			cp /etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf{.allow,}
			rm /etc/shutdown.allow
		fi
	fi
}

run_salt
